application: ballin-octo-wallhack
version: 1-13-0
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.application
  login: admin

libraries:
- name: jinja2
  version: latest
